### ISSUE TITLE
Fix MySQL dialect

### ISSUE THREAD

**Issue by adrien-berchet** [geoalchemy/geoalchemy2#467]
MySQL dialect is not completely working, as shown in this test: https://github.com/geoalchemy/geoalchemy2/blob/master/tests/test_functional.py#L436
This probably points a deep issue in MySQL support so we have to understand why it fails and fix it.

**Comment by satyamsoni2211** [comment]
@adrien-berchet I think my fix should fix this issue as well.

**Comment by adrien-berchet** [comment]
I tried to rerun the failing test with the new release and unfortunately it still fails (this test: `tests/test_functional.py::TestInsertionORM::test_transform[mysql]`).

**Comment by adrien-berchet** [comment]
Fixed in #567
